const key = 'pk.eyJ1IjoicHduZWlsbCIsImEiOiJja2R6N3JhYzkzazZwMnJxcXB0Y3V0NHQ5In0.IU5S18FiNleGSzGcIOxZWA'

const locationData = [{
          "id": 1,
          "name": "Heartland Alliance - Uptown",
          "desc": "Heartland Alliance Health Centers mental health services include: counseling for individuals and groups, addiction services, trauma and post-trauma counseling, and in-network provider referrals.",
          "lat": 41.9689469,
          "lng": -87.6575813,
          "hours":"8:00am - 5:00pm",
          "addr1": "1015 W Lawrence Ave",
          "addr2": "Chicago IL 60640",
          "phone": "(773) 275-2586",
          "web": "https://www.heartlandalliance.org/",
          "waitTime": "one week",
          "telehealth": "yes",
          "languages": "Spanish",
          "financialAssistance": "Yes, they offer income-based repayment",
          "ageRestrictions": "no",
          "appointment": "yes",
          "medicaid": "yes",
          "LGBT": "yes",
          
        },{
            "id": 2,
            "name": "Heartland Alliance - James West",
            "desc": "Heartland Alliance Health Centers mental health services include: counseling for individuals and groups, addiction services, trauma and post-trauma counseling, and in-network provider referrals.",
            "lat": 41.8832628,
            "lng": -87.653475,
            "hours":"8:00am - 5:00pm",
            "addr1": "932 W Washington Blvd #224",
            "addr2": "Chicago IL 60607",
            "phone": "(773) 275-2586",
            "web": "https://www.heartlandalliance.org/",
            "waitTime": "one week",
            "telehealth": "yes",
            "languages": "Spanish",
            "financialAssistance": "Yes, they offer income-based repayment",
            "ageRestrictions": "no",
            "appointment": "yes",
            "medicaid": "yes",
            "LGBT": "yes",
          },{
            "id": 3,
            "name": "Heartland Alliance - Englewood",
            "desc": "Heartland Alliance Health Centers mental health services include: counseling for individuals and groups, addiction services, trauma and post-trauma counseling, and in-network provider referrals.",
            "lat": 41.79369,
            "lng": -87.647019,
            "hours":"8:30am - 5:00pm",
            "waitTime": "one week",
            "addr1": "5501 S Haldstead St",
            "addr2": "Chicago IL 60621",
            "phone": "(773) 275-2586",
            "web": "https://www.heartlandalliance.org/",
            "telehealth": "yes",
            "languages": "Spanish",
            "financialAssistance": "Yes, they offer income-based repayment",
            "ageRestrictions": "no",
            "appointment": "yes",
            "medicaid": "yes",
            "LGBT": "yes",
          },{
            "id": 4,
            "name": "Children's Home & Aid",
            "desc": "Children's Home and Aid provides a variety of different mental health services. The Behavioral Health Services program provides school based, office based and community-based services to children and youth ages 4-21 and their families on the west and south sides of Chicago. Program staff members are sensitive to all cultural values, sexual orientations, and gender identities.",
            "lat": 41.881760,
            "lng": -87.637090,
            "hours": "8:30am - 4:30pm",
            "addr1": "125 South Wacker Drive, 14th Floor",
            "addr2": "Chicago IL 60606",
            "phone": "(773) 969-5524",
            "waitTime": "one week",
            "web": "https://childrenshomeandaid.org/",
            "telehealth": "no",
            "languages": "Spanish",
            "financialAssistance": "Yes, they offer income-based repayment for patients with Medicaid",
            "ageRestrictions": "4-21",
            "appointment": "yes",
            "medicaid": "yes",
            "LGBT": "yes",
          },{
            "id": 5,
            "name": "Alternatives, Inc.",
            "desc": "Alternatives, Inc. provides services to youth (0-18) with short-and long-term therapy and case management, emphasizing family communication, conflict resolution, discipline, and life-skills development. Individual, family, and group services are offered through school-based health centers, and within our Youth Center to support youth experiencing a range of issues, including family conflict, substance abuse, peer relationships, identity issues, anger management, and behavioral/emotional challenges.",
            "hours": "8:30am-5:00pm",
            "lat": 41.8797103,
            "lng": -87.6386053,
            "waitTime": "varies",
            "addr1": "4730 North Sheridan Road",
            "addr2": "Chicago, IL 60640",
            "phone": "(773) 506--7474",
            "web": "alternativesyouth.org/contact/",
            "telehealth": "no",
            "languages": "Spanish",
            "financialAssistance": "Yes, they offer income-based repayment",
            "ageRestrictions": "available to youth up to 18 years old",
            "appointment": "yes",
            "medicaid": "yes",
            "LGBT": "yes",
          },{
            "id": 6,
            "name": "Metropolitan Family Services - South Side (Calumet Center)",
            "desc": "Short and long term counseling services available to adults, children, and families. Metropolitan Family services focuses on Adult Mental Health, Children and Adolescent Mental Health, and Senior Counseling. In addition to counseling, they also have in-home respite, adult protective services, and support for caregivers, homeowners, and grandparents raising grandchildren.",
            "lat": 41.7070137,
            "lng": -87.6189035,
            "hours": "8:30am-5:00pm",
            "waitTime": "1-2 Weeks",
            "addr1": "235 E 103rd St",
            "addr2": "Chicago, IL 60628",
            "phone": "(773) 506-7474",
            "web": "metrofamily.org/contact-us/",
            "telehealth": "no",
            "languages": "Spanish",
            "financialAssistance": "Yes, they offer income-based repayment",
            "ageRestrictions": "no",
            "appointment": "yes",
            "medicaid": "yes",
            "LGBT": "yes",
          },{
            "id": 7,
            "name": "Metropolitan Family Services - Midway",
            "desc": "Short and long term counseling services available to adults, children, and families. Metropolitan Family services focuses on Adult Mental Health, Children and Adolescent Mental Health, and Senior Counseling. In addition to counseling, they also have in-home respite, adult protective services, and support for caregivers, homeowners, and grandparents raising grandchildren.",
            "lat": 41.7784327,
            "lng": -87.7216876,
            "hours": "8:30am-5:00pm",
            "waitTime": "1-2 Weeks",
            "addr1": "3843 West 63rd Street",
            "addr2": "Chicago, IL 60628",
            "phone": "(773) 884-3310",
            "web": "metrofamily.org/contact-us/",
            "telehealth": "no",
            "languages": "Spanish",
            "financialAssistance": "no",
            "ageRestrictions": "available to youth up to 18 years old",
            "appointment": "yes",
            "medicaid": "yes",
            "LGBT": "yes",
          },{
            "id": 8,
            "name": "Metropolitan Family Services - Southeast Chicago",
            "desc": "Short and long term counseling services available to adults, children, and families. Metropolitan Family services focuses on Adult Mental Health, Children and Adolescent Mental Health, and Senior Counseling. In addition to counseling, they also have in-home respite, adult protective services, and support for caregivers, homeowners, and grandparents raising grandchildren.",
            "lat": 41.7302826,
            "lng": -87.5510891,
            "hours": "8:30am-5:00pm",
            "waitTime": "1-2 Weeks",
            "addr1": "3062 East 91st Street",
            "addr2": "Chicago, IL 60617",
            "phone": "(773) 371-2900",
            "web": "metrofamily.org/contact-us/",
            "telehealth": "no",
            "languages": "Spanish",
            "financialAssistance": "Yes, they offer income-based repayment",
            "ageRestrictions": "no",
            "appointment": "yes",
            "medicaid": "yes",
            "LGBT": "yes",
          },{
            "id": 9,
            "name": "Metropolitan Family Services - Northside",
            "desc": "Short and long term counseling services available to adults, children, and families. Metropolitan Family services focuses on Adult Mental Health, Children and Adolescent Mental Health, and Senior Counseling. In addition to counseling, they also have in-home respite, adult protective services, and support for caregivers, homeowners, and grandparents raising grandchildren.",
            "hours": "8:30am-5:00pm",
            "lat": 41.940151,
            "lng": -87.768352,
            "waitTime": "1-2 Weeks",
            "addr1": "3249 North Central Ave",
            "addr2": "Chicago, IL 60634",
            "phone": "(773) 371-3700",
            "web": "metrofamily.org/contact-us/",
            "telehealth": "no",
            "languages": "Spanish",
            "financialAssistance": "Yes, they offer income-based repayment",
            "ageRestrictions": "no",
            "appointment": "yes",
            "medicaid": "yes",
            "LGBT": "yes",
          },{
            "id": 10,
            "name": "Metropolitan Family Services - DuPage",
            "desc": "Short and long term counseling services available to adults, children, and families. Metropolitan Family services focuses on Adult Mental Health, Children and Adolescent Mental Health, and Senior Counseling. In addition to counseling, they also have in-home respite, adult protective services, and support for caregivers, homeowners, and grandparents raising grandchildren.",
            "hours": "8:30am-5:00pm",
            "lat": 41.9142883,
            "lng": -87.6379722,
            "waitTime": "1-2 Weeks",
            "addr1": "222 East Willow Ave",
            "addr2": "Wheaton, IL 60187",
            "phone": "(630) 784-4800",
            "web": "metrofamily.org/contact-us/",
            "telehealth": "no",
            "languages": "Spanish",
            "financialAssistance": "Yes, they offer income-based repayment",
            "ageRestrictions": "no",
            "appointment": "yes",
            "medicaid": "yes",
            "LGBT": "yes",
          },{
            "id": 11,
            "name": "Metropolitan Family Services - Southwest Suburbs",
            "desc": "Short and long term counseling services available to adults, children, and families. Metropolitan Family services focuses on Adult Mental Health, Children and Adolescent Mental Health, and Senior Counseling. In addition to counseling, they also have in-home respite, adult protective services, and support for caregivers, homeowners, and grandparents raising grandchildren.",
            "hours": "8:30am-5:00pm",
            "lat": 41.654263,
            "lng": -87.6823584,
            "waitTime": "1-2 Weeks",
            "addr1": "13136 Western Ave",
            "addr2": "Blue Island, IL 60406",
            "phone": "(708) 974-2300",
            "web": "metrofamily.org/contact-us/",
            "telehealth": "no",
            "languages": "Spanish",
            "financialAssistance": "Yes, they offer income-based repayment",
            "ageRestrictions": "no",
            "appointment": "yes",
            "medicaid": "yes",
            "LGBT": "yes",
          },{
            "id": 12,
            "name": "Metropolitan Family Services - Palos Hills",
            "desc": "Short and long term counseling services available to adults, children, and families. Metropolitan Family services focuses on Adult Mental Health, Children and Adolescent Mental Health, and Senior Counseling. In addition to counseling, they also have in-home respite, adult protective services, and support for caregivers, homeowners, and grandparents raising grandchildren.",
            "hours": "8:30am-5:00pm",
            "lat": 41.6991067,
            "lng": -87.8186719,
            "waitTime": "1-2 Weeks",
            "addr1": "10537 South Roberts Rd",
            "addr2": "Palos Hills, IL 60465",
            "phone": "(708) 974-2300",
            "web": "metrofamily.org/contact-us/",
            "telehealth": "no",
            "languages": "Spanish",
            "financialAssistance": "Yes, they offer income-based repayment",
            "ageRestrictions": "no",
            "appointment": "yes",
            "medicaid": "yes",
            "LGBT": "yes",
          },{
            "id": 13,
            "name": "Thresholds",
            "desc": "Thresholds provides clinical services for people with severe mental illness (must be already diagnosed/assessed and on Medicaid). This includes case management, psychiatric care, group and individual therapy, as well as the evidence-based practices of Wellness Management and Recovery and Integrated Dual Disorders Treatment.",
            "hours": "9:00am-5:00pm",
            "lat": 41.9622476,
            "lng": -87.6759463,
            "waitTime": "3-4 Weeks",
            "addr1": "4101 N Ravenswood Ave",
            "addr2": "Chicago, IL 60613",
            "phone": "(773) 572-5500",
            "web": "thresholds.org",
            "telehealth": "yes",
            "languages": "Spanish",
            "financialAssistance": "Medicaid Only",
            "ageRestrictions": "young adults aged 16-20",
            "appointment": "yes",
            "medicaid": "yes",
            "LGBT": "yes",
          },{
            "id": 14,
            "name": "Heartland Health Centers - Trilogy",
            "desc": "Heartland Health Centers offers counseling, psychiatry, and behavioral health for patients who already have their primarcy care provider at Heartland",
            "hours": "8:45am-4:00pm",
            "lat": 42.0105454,
            "lng": -87.6687147,
            "waitTime": "varies",
            "addr1": "1400 W Greenleaf Ave",
            "addr2": "Chicago, IL 60626",
            "phone": "(773) 751-7800",
            "web": "heartlandhealthcenters.org/",
            "telehealth": "unknown",
            "languages": "Spanish",
            "financialAssistance": "Yes, it depends on your situation but fees range from $30 to $80 and up",
            "ageRestrictions": "no",
            "appointment": "yes",
            "medicaid": "Yes, as long as Heartland is assigned as the PCP",            "LGBT": "yes",
          },{
            "id": 15,
            "name": "Heartland Health Centers - Thresholds",
            "desc": "Heartland Health Centers offers counseling, psychiatry, and behavioral health for patients who already have their primarcy care provider at Heartland",
            "hours": "8:45am-4:00pm",
            "lat": 41.9622516,
            "lng": -87.6759516,
            "waitTime": "varies",
            "addr1": "4423 N Ravenswood Ave",
            "addr2": "Chicago, IL 60640",
            "phone": "(773) 432-6570",
            "web": "heartlandhealthcenters.org/",
            "telehealth": "unknown",
            "languages": "Spanish",
            "financialAssistance": "Yes, it depends on your situation but fees range from $30 to $80 and up",
            "ageRestrictions": "no",
            "appointment": "yes",
            "medicaid": "Yes, as long as Heartland is assigned as the PCP",
            "LGBT": "yes",
          },{
            "id": 16,
            "name": "Heartland Health Centers - C4 Broadway",
            "desc": "Heartland Health Centers offers counseling, psychiatry, and behavioral health for patients who already have their primarcy care provider at Heartland",
            "hours": "8:45am-4:00pm",
            "lat": 41.958140,
            "lng": -87.652810,
            "waitTime": "varies",
            "addr1": "45710 N Broadway St",
            "addr2": "Chicago, IL 60660",
            "phone": "(773) 728-1000",
            "web": "heartlandhealthcenters.org/",
            "telehealth": "unknown",
            "languages": "Spanish",
            "financialAssistance": "Yes, it depends on your situation but fees range from $30 to $80 and up",
            "ageRestrictions": "no",
            "appointment": "yes",
            "medicaid": "Yes, as long as Heartland is assigned as the PCP",
            "LGBT": "yes",
          },{
            "id": 17,
            "name": "Heartland Health Centers - Harrison Street",
            "desc": "Heartland Health Centers offers counseling, psychiatry, and behavioral health for patients who already have their primarcy care provider at Heartland",
            "hours": "8:45am-4:00pm",
            "lat": 41.8736238,
            "lng": -87.7038249,
            "waitTime": "varies",
            "addr1": "3015 W Harrison St",
            "addr2": "Chicago, IL 60612",
            "phone": "(773) 728-1000",
            "web": "heartlandhealthcenters.org/",
            "telehealth": "unknown",
            "languages": "Spanish",
            "financialAssistance": "Yes, it depends on your situation but fees range from $30 to $80 and up",
            "ageRestrictions": "no",
            "appointment": "yes",
            "medicaid": "Yes, as long as Heartland is assigned as the PCP",
            "LGBT": "yes",
          },{
            "id": 18,
            "name": "NAMI Chicago",
            "desc": "NAMI Chicago's free and confidential Helpline is open seven days a week, staffed by clinicians and peers who can guide you through types of treatment, lend a compassionate ear, connect you to legal and housing support, and can also provide resources for mental health professionals and clinicians. We are there for family members, individuals, friends, and communities in need of mental health support",
            "hours": "Monday - Friday, 9:00am- 8:00pm Saturday - Sunday, 9:00am- 5:00pm",
            "lat": 41.956732,
            "lng": -87.6767327,
            "waitTime": "The helpline can refer you to a counselor. The wait time may depend on your specific needs",
            "addr1": "1801 W Warner Ave Suite 202",
            "addr2": "Chicago, IL 60613",
            "phone": "(833) 626-4244",
            "web": "www.namichicago.org/",
            "telehealth": "yes",
            "languages": "Spanish",
            "financialAssistance": "the referral is free",
            "ageRestrictions": "No, anyone can use this service",
            "appointment": "yes",
            "medicaid": "there's no fee for this service",
            "LGBT": "yes",
          },{
            "id": 19,
            "name": "Catholic Charities - Youth and Family Therapeutic Services",
            "desc": "The Youth and Family Therapeutic Services provides trauma informed and strengths-based counseling services to children and families through a variety of counseling programs. Individual, family and group sessions assist children and families experiencing a wide range of social and personal problems impacting their ability to cope. The program accepts children and families throughout Cook County.",
            "hours": "8:30am to 4:30pm",
            "lat": 41.8666376,
            "lng": -87.6864489,
            "waitTime": "The helpline can refer you to a counselor. The wait time may depend on your specific needs",
            "addr1": "2310 W. Roosevelt 2nd Fl",
            "addr2": "Chicago, IL 60608",
            "phone": "(312) 655-7191",
            "web": "catholiccharities.net/",
            "telehealth": "no",
            "languages": "Spanish",
            "financialAssistance": "Subsidized fee available based on household and income size.",
            "ageRestrictions": "yes, ages 3-18",
            "appointment": "yes",
            "medicaid": "yes",
            "LGBT": "yes",
          }]
          // },{
          //   "id": 18,
          //   "name": "NAMI Chicago",
          //   "desc": "NAMI Chicago's free and confidential Helpline is open seven days a week, staffed by clinicians and peers who can guide you through types of treatment, lend a compassionate ear, connect you to legal and housing support, and can also provide resources for mental health professionals and clinicians. We are there for family members, individuals, friends, and communities in need of mental health support",
          //   "hours": "Monday - Friday, 9:00am- 8:00pm Saturday - Sunday, 9:00am- 5:00pm",
          //   "lat": 41.956732,
          //   "lng": -87.6767327,
          //   "waitTime": "The helpline can refer you to a counselor. The wait time may depend on your specific needs",
          //   "addr1": "1801 W Warner Ave Suite 202",
          //   "addr2": "Chicago, IL 60613",
          //   "phone": "(833) 626-4244",
          //   "web": "www.namichicago.org/",
          //   "telehealth": "yes",
          //   "languages": "Spanish",
          //   "financialAssistance": "the referral is free",
          //   "ageRestrictions": "no",
          //   "appointment": "yes",
          //   "medicaid": "yes",
          //   "LGBT": "yes",
          // },{
          //   "id": 18,
          //   "name": "NAMI Chicago",
          //   "desc": "NAMI Chicago's free and confidential Helpline is open seven days a week, staffed by clinicians and peers who can guide you through types of treatment, lend a compassionate ear, connect you to legal and housing support, and can also provide resources for mental health professionals and clinicians. We are there for family members, individuals, friends, and communities in need of mental health support",
          //   "hours": "Monday - Friday, 9:00am- 8:00pm Saturday - Sunday, 9:00am- 5:00pm",
          //   "lat": 41.956732,
          //   "lng": -87.6767327,
          //   "waitTime": "The helpline can refer you to a counselor. The wait time may depend on your specific needs",
          //   "addr1": "1801 W Warner Ave Suite 202",
          //   "addr2": "Chicago, IL 60613",
          //   "phone": "(833) 626-4244",
          //   "web": "www.namichicago.org/",
          //   "telehealth": "yes",
          //   "languages": "Spanish",
          //   "financialAssistance": "the referral is free",
          //   "ageRestrictions": "no",
          //   "appointment": "yes",
          //   "medicaid": "yes",
          //   "LGBT": "yes",
          // },{
          //   "id": 18,
          //   "name": "NAMI Chicago",
          //   "desc": "NAMI Chicago's free and confidential Helpline is open seven days a week, staffed by clinicians and peers who can guide you through types of treatment, lend a compassionate ear, connect you to legal and housing support, and can also provide resources for mental health professionals and clinicians. We are there for family members, individuals, friends, and communities in need of mental health support",
          //   "hours": "Monday - Friday, 9:00am- 8:00pm Saturday - Sunday, 9:00am- 5:00pm",
          //   "lat": 41.956732,
          //   "lng": -87.6767327,
          //   "waitTime": "The helpline can refer you to a counselor. The wait time may depend on your specific needs",
          //   "addr1": "1801 W Warner Ave Suite 202",
          //   "addr2": "Chicago, IL 60613",
          //   "phone": "(833) 626-4244",
          //   "web": "www.namichicago.org/",
          //   "telehealth": "yes",
          //   "languages": "Spanish",
          //   "financialAssistance": "the referral is free",
          //   "ageRestrictions": "no",
          //   "appointment": "yes",
          //   "medicaid": "yes",
          //   "LGBT": "yes",
          // },{
          //   "id": 18,
          //   "name": "NAMI Chicago",
          //   "desc": "NAMI Chicago's free and confidential Helpline is open seven days a week, staffed by clinicians and peers who can guide you through types of treatment, lend a compassionate ear, connect you to legal and housing support, and can also provide resources for mental health professionals and clinicians. We are there for family members, individuals, friends, and communities in need of mental health support",
          //   "hours": "Monday - Friday, 9:00am- 8:00pm Saturday - Sunday, 9:00am- 5:00pm",
          //   "lat": 41.956732,
          //   "lng": -87.6767327,
          //   "waitTime": "The helpline can refer you to a counselor. The wait time may depend on your specific needs",
          //   "addr1": "1801 W Warner Ave Suite 202",
          //   "addr2": "Chicago, IL 60613",
          //   "phone": "(833) 626-4244",
          //   "web": "www.namichicago.org/",
          //   "telehealth": "yes",
          //   "languages": "Spanish",
          //   "financialAssistance": "the referral is free",
          //   "ageRestrictions": "no",
          //   "appointment": "yes",
          //   "medicaid": "yes",
          //   "LGBT": "yes",
          // },{
          //   "id": 18,
          //   "name": "NAMI Chicago",
          //   "desc": "NAMI Chicago's free and confidential Helpline is open seven days a week, staffed by clinicians and peers who can guide you through types of treatment, lend a compassionate ear, connect you to legal and housing support, and can also provide resources for mental health professionals and clinicians. We are there for family members, individuals, friends, and communities in need of mental health support",
          //   "hours": "Monday - Friday, 9:00am- 8:00pm Saturday - Sunday, 9:00am- 5:00pm",
          //   "lat": 41.956732,
          //   "lng": -87.6767327,
          //   "waitTime": "The helpline can refer you to a counselor. The wait time may depend on your specific needs",
          //   "addr1": "1801 W Warner Ave Suite 202",
          //   "addr2": "Chicago, IL 60613",
          //   "phone": "(833) 626-4244",
          //   "web": "www.namichicago.org/",
          //   "telehealth": "yes",
          //   "languages": "Spanish",
          //   "financialAssistance": "the referral is free",
          //   "ageRestrictions": "no",
          //   "appointment": "yes",
          //   "medicaid": "yes",
          //   "LGBT": "yes",
          // }]

var markerIcon = L.Icon.extend({ 
    options: {
        customId: ""
    }
})

var mymap = L.map('mapid').setView([41.81944, -87.327778], 9.9);

L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    maxZoom: 18,
    id: 'mapbox/streets-v11',
    tileSize: 512,
    zoomOffset: -1,
    accessToken: key
}).addTo(mymap);

var sidebar = L.control.sidebar('sidebar', {
    position: 'left'
});

mymap.addControl(sidebar);

locationData.forEach(loc => {

    L.marker([loc.lat, loc.lng], {customId: loc.id}).addTo(mymap).on('click', function () {
        console.log(this.options.customId)

        let location = locationData[this.options.customId]
        let html = generateContent(location)
        sidebar.setContent(html);

        sidebar.toggle();
    });
})

function generateContent(loc) {
    return `
    <div>
    <h1 id="sidebar-name">${loc.name}</h1>
    <p id="sidebar-desc">${loc.desc}</p>
    <p id="sidebar-desc"><b>Address: </br>${loc.addr1}<br/>${loc.addr2}</p>
    <p id="sidebar-hours"><b>Hours: </b>${loc.hours}</p>
    <p id="sidebar-wait"><b>Average wait time: </b>${loc.waitTime}</p>
    <p id="sidebar-phone">${loc.phone}</p>
    <p id="sidebar-desc"><a href=${loc.web}>${loc.web}</a></p>    
    <p id="sidebar-telehealth"><br>Does this location offer telehealth services? </b>${loc.telehealth}</p>
    <p id="sidebar-lang><b>Languages Served: </b>${loc.languages}
    <p id="sidebar-financing"><b>Does this location offer financial assistance? </b>${loc.financialAssistance}</p>
    <p id="sidebar-ages"><b>Are there any age limits? </b>${loc.ageRestrictions}</p>
    <p id="sidebar-appointment"><b>Do you need an appointment? </b>${loc.appointment}</p>
    <p id="sidebar-medicaid"><b>Do they take Medicaid? </b>${loc.medicaid}</p>
    <p id="sidebar-lgbt"><b>Are they queer friendly?  </b>${loc.LGBT}</p>
    <p id="sidebar-lgbt-1"><b>Are they queer friendly?  </b>${loc.LGBT}</p>

    </div>
    `
}